apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project-sorting
  namespace: demo-project-sorting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-project-sorting
  template:
    metadata:
      labels:
        app: demo-project-sorting
    spec:
      containers:
        - name: demo-project-sorting
          image: demo-project-sorting:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-project-sorting
  namespace: demo-project-sorting
spec:
  type: NodePort
  selector:
    app: demo-project-sorting
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
