apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project-sorting:null
  namespace: demo-project-sorting:null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-project-sorting:null
  template:
    metadata:
      labels:
        app: demo-project-sorting:null
    spec:
      containers:
        - name: demo-project-sorting:null
          image: usamaahmed99/demo-project-sorting:null
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-project-sorting:null
  namespace: demo-project-sorting:null
spec:
  type: NodePort
  selector:
    app: demo-project-sorting:null
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
